# Generated by Django 3.0.3 on 2020-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
