# Generated by Django 3.0.3 on 2020-02-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20200206_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
